//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contacto.Lib {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DBIOMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DBIOMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Contacto.Lib.DBIOMessages", typeof(DBIOMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking blob filename duplication failed..
        /// </summary>
        internal static string CheckBlobFilenameDuplicateFailed {
            get {
                return ResourceManager.GetString("CheckBlobFilenameDuplicateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking company duplicates failed..
        /// </summary>
        internal static string CheckCompanyDuplicatesFailed {
            get {
                return ResourceManager.GetString("CheckCompanyDuplicatesFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking in blob failed..
        /// </summary>
        internal static string CheckInBlobFailed {
            get {
                return ResourceManager.GetString("CheckInBlobFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking out blob failed..
        /// </summary>
        internal static string CheckOutBlobFailed {
            get {
                return ResourceManager.GetString("CheckOutBlobFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking person duplicates failed..
        /// </summary>
        internal static string CheckPersonDuplicatesFailed {
            get {
                return ResourceManager.GetString("CheckPersonDuplicatesFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closing entity failed..
        /// </summary>
        internal static string CloseEntityFailed {
            get {
                return ResourceManager.GetString("CloseEntityFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating blob failed..
        /// </summary>
        internal static string CreateBlobFailed {
            get {
                return ResourceManager.GetString("CreateBlobFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating company failed..
        /// </summary>
        internal static string CreateCompanyFailed {
            get {
                return ResourceManager.GetString("CreateCompanyFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating document failed..
        /// </summary>
        internal static string CreateDocumentFailed {
            get {
                return ResourceManager.GetString("CreateDocumentFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating entity failed..
        /// </summary>
        internal static string CreateEntityFailed {
            get {
                return ResourceManager.GetString("CreateEntityFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating folder failed..
        /// </summary>
        internal static string CreateFolderFailed {
            get {
                return ResourceManager.GetString("CreateFolderFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating new user login failed..
        /// </summary>
        internal static string CreateLoginFailed {
            get {
                return ResourceManager.GetString("CreateLoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating person failed..
        /// </summary>
        internal static string CreatePersonFailed {
            get {
                return ResourceManager.GetString("CreatePersonFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting entity failed..
        /// </summary>
        internal static string DeleteEntityFailed {
            get {
                return ResourceManager.GetString("DeleteEntityFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting user login failed..
        /// </summary>
        internal static string DeleteLoginFailed {
            get {
                return ResourceManager.GetString("DeleteLoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute with the specified type already exist..
        /// </summary>
        internal static string DuplicateAttribute {
            get {
                return ResourceManager.GetString("DuplicateAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity not saved. Must be saved before adding any attribute..
        /// </summary>
        internal static string EntityNotSaved {
            get {
                return ResourceManager.GetString("EntityNotSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading schema..
        /// </summary>
        internal static string ErrorLoadingSchema {
            get {
                return ResourceManager.GetString("ErrorLoadingSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finding companies failed..
        /// </summary>
        internal static string FindCompaniesFailed {
            get {
                return ResourceManager.GetString("FindCompaniesFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Findind documents failed..
        /// </summary>
        internal static string FindDocumentsFailed {
            get {
                return ResourceManager.GetString("FindDocumentsFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finding entities failed..
        /// </summary>
        internal static string FindEntitiesFailed {
            get {
                return ResourceManager.GetString("FindEntitiesFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finding folders failed..
        /// </summary>
        internal static string FindFoldersFailed {
            get {
                return ResourceManager.GetString("FindFoldersFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting blob data failed..
        /// </summary>
        internal static string GetBlobDataFailed {
            get {
                return ResourceManager.GetString("GetBlobDataFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid version. The entity might be modified by other user..
        /// </summary>
        internal static string InvalidVersion {
            get {
                return ResourceManager.GetString("InvalidVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading addresses failed..
        /// </summary>
        internal static string LoadAddressesFailed {
            get {
                return ResourceManager.GetString("LoadAddressesFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading blob failed..
        /// </summary>
        internal static string LoadBlobFailed {
            get {
                return ResourceManager.GetString("LoadBlobFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading blobs failed..
        /// </summary>
        internal static string LoadBlobsFailed {
            get {
                return ResourceManager.GetString("LoadBlobsFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading categories failed..
        /// </summary>
        internal static string LoadCategoriesFailed {
            get {
                return ResourceManager.GetString("LoadCategoriesFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading category descriptions failed..
        /// </summary>
        internal static string LoadCategoryDescriptionsFailed {
            get {
                return ResourceManager.GetString("LoadCategoryDescriptionsFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading company failed..
        /// </summary>
        internal static string LoadCompanyFailed {
            get {
                return ResourceManager.GetString("LoadCompanyFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading dates failed..
        /// </summary>
        internal static string LoadDatesFailed {
            get {
                return ResourceManager.GetString("LoadDatesFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading document failed..
        /// </summary>
        internal static string LoadDocumentFailed {
            get {
                return ResourceManager.GetString("LoadDocumentFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading documents failed..
        /// </summary>
        internal static string LoadDocumentsFailed {
            get {
                return ResourceManager.GetString("LoadDocumentsFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading folder failed..
        /// </summary>
        internal static string LoadFolderFailed {
            get {
                return ResourceManager.GetString("LoadFolderFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading identifiers failed..
        /// </summary>
        internal static string LoadIdentifiersFailed {
            get {
                return ResourceManager.GetString("LoadIdentifiersFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading links failed..
        /// </summary>
        internal static string LoadLinksFailed {
            get {
                return ResourceManager.GetString("LoadLinksFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading person failed..
        /// </summary>
        internal static string LoadPersonFailed {
            get {
                return ResourceManager.GetString("LoadPersonFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading persons failed..
        /// </summary>
        internal static string LoadPersonsFailed {
            get {
                return ResourceManager.GetString("LoadPersonsFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading type descriptions failed..
        /// </summary>
        internal static string LoadTypeDescriptionsFailed {
            get {
                return ResourceManager.GetString("LoadTypeDescriptionsFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading users failed..
        /// </summary>
        internal static string LoadUsersFailed {
            get {
                return ResourceManager.GetString("LoadUsersFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login failed..
        /// </summary>
        internal static string LoginFailed {
            get {
                return ResourceManager.GetString("LoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logoff failed..
        /// </summary>
        internal static string LogoffFailed {
            get {
                return ResourceManager.GetString("LogoffFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifying blob failed..
        /// </summary>
        internal static string ModifyBlobFailed {
            get {
                return ResourceManager.GetString("ModifyBlobFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifying company failed..
        /// </summary>
        internal static string ModifyCompanyFailed {
            get {
                return ResourceManager.GetString("ModifyCompanyFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifying document failed..
        /// </summary>
        internal static string ModifyDocumentFailed {
            get {
                return ResourceManager.GetString("ModifyDocumentFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifying entity failed..
        /// </summary>
        internal static string ModifyEntityFailed {
            get {
                return ResourceManager.GetString("ModifyEntityFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifying folder failed..
        /// </summary>
        internal static string ModifyFolderFailed {
            get {
                return ResourceManager.GetString("ModifyFolderFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifying person failed..
        /// </summary>
        internal static string ModifyPersonFailed {
            get {
                return ResourceManager.GetString("ModifyPersonFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating new blob failed..
        /// </summary>
        internal static string NewBlobFailed {
            get {
                return ResourceManager.GetString("NewBlobFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating new document failed..
        /// </summary>
        internal static string NewDocumentFailed {
            get {
                return ResourceManager.GetString("NewDocumentFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating new person failed..
        /// </summary>
        internal static string NewPersonFailed {
            get {
                return ResourceManager.GetString("NewPersonFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening closed entity failed..
        /// </summary>
        internal static string OpenEntityFailed {
            get {
                return ResourceManager.GetString("OpenEntityFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recovering entity failed..
        /// </summary>
        internal static string RecoverEntityFailed {
            get {
                return ResourceManager.GetString("RecoverEntityFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving required addresses failed..
        /// </summary>
        internal static string SaveRequiredAddressesFailed {
            get {
                return ResourceManager.GetString("SaveRequiredAddressesFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Savig required categories failed..
        /// </summary>
        internal static string SaveRequiredCategoriesFailed {
            get {
                return ResourceManager.GetString("SaveRequiredCategoriesFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving required dates failed..
        /// </summary>
        internal static string SaveRequiredDatesFailed {
            get {
                return ResourceManager.GetString("SaveRequiredDatesFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving required indentifiers failed..
        /// </summary>
        internal static string SaveRequiredIdentifiersFailed {
            get {
                return ResourceManager.GetString("SaveRequiredIdentifiersFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving required links failed..
        /// </summary>
        internal static string SaveRequiredLinksFailed {
            get {
                return ResourceManager.GetString("SaveRequiredLinksFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting blob data failed..
        /// </summary>
        internal static string SetBlobDataFailed {
            get {
                return ResourceManager.GetString("SetBlobDataFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating blob data failed..
        /// </summary>
        internal static string UpdateBlobDataFailed {
            get {
                return ResourceManager.GetString("UpdateBlobDataFailed", resourceCulture);
            }
        }
    }
}
