//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contacto.UI {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Contacto.UI.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nem hozható létre új dátum..
        /// </summary>
        internal static string CannotCreateDate {
            get {
                return ResourceManager.GetString("CannotCreateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nem hozható létre új hivatkozás..
        /// </summary>
        internal static string CannotCreateLink {
            get {
                return ResourceManager.GetString("CannotCreateLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Az elem nem törölhető..
        /// </summary>
        internal static string CannotDelete {
            get {
                return ResourceManager.GetString("CannotDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Az elem nem módosítható..
        /// </summary>
        internal static string CannotModify {
            get {
                return ResourceManager.GetString("CannotModify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lezárva.
        /// </summary>
        internal static string Closed {
            get {
                return ResourceManager.GetString("Closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valóban meg kívánja változtatni a fájl kiterjesztését?.
        /// </summary>
        internal static string ConfirmChangeExtension {
            get {
                return ResourceManager.GetString("ConfirmChangeExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valóban törölni szeretné a kijelölt elemeket?.
        /// </summary>
        internal static string ConfirmDelete {
            get {
                return ResourceManager.GetString("ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valóban törölni szeretné a következő elemet: {0}?.
        /// </summary>
        internal static string ConfirmDeleteEntity {
            get {
                return ResourceManager.GetString("ConfirmDeleteEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Törölve.
        /// </summary>
        internal static string Deleted {
            get {
                return ResourceManager.GetString("Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Már létező fájlnév. Törölje a régit..
        /// </summary>
        internal static string DuplicateBlobFilename {
            get {
                return ResourceManager.GetString("DuplicateBlobFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiba történt a fájl szerkesztésének befejezésekor. Elképzelhető, hogy a fájl még valamelyik programban meg van nyitva. A műveletet megszakíthatja, megpróbálhatja ismét, illetve figyelmen kívül hagyhatja a hibát, de ekkor a legutolsó változtatások elveszhetnek..
        /// </summary>
        internal static string ErrorCheckinBlob {
            get {
                return ResourceManager.GetString("ErrorCheckinBlob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiba történt a fájl megnyitásakor..
        /// </summary>
        internal static string ErrorCheckoutBlob {
            get {
                return ResourceManager.GetString("ErrorCheckoutBlob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiba történt az elem lezárásakor..
        /// </summary>
        internal static string ErrorClosingEntity {
            get {
                return ResourceManager.GetString("ErrorClosingEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiba történt az új cím létrehozása közben..
        /// </summary>
        internal static string ErrorCreatingAddress {
            get {
                return ResourceManager.GetString("ErrorCreatingAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiba történt a fájl létrehozása közben..
        /// </summary>
        internal static string ErrorCreatingBlob {
            get {
                return ResourceManager.GetString("ErrorCreatingBlob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiba történt az új kategória létrehozásakor..
        /// </summary>
        internal static string ErrorCreatingCategory {
            get {
                return ResourceManager.GetString("ErrorCreatingCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiba történt az új cég létrehozása közben..
        /// </summary>
        internal static string ErrorCreatingCompany {
            get {
                return ResourceManager.GetString("ErrorCreatingCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiba történt az új dátum létrehozásakor..
        /// </summary>
        internal static string ErrorCreatingDate {
            get {
                return ResourceManager.GetString("ErrorCreatingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiba történt a dokumentum létrehozása közben..
        /// </summary>
        internal static string ErrorCreatingDocument {
            get {
                return ResourceManager.GetString("ErrorCreatingDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiba történt az új elem létrehozásakor..
        /// </summary>
        internal static string ErrorCreatingEntity {
            get {
                return ResourceManager.GetString("ErrorCreatingEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiba történt a mappa létrehozása közben..
        /// </summary>
        internal static string ErrorCreatingFolder {
            get {
                return ResourceManager.GetString("ErrorCreatingFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiba történt az azonosító létrehozásakor..
        /// </summary>
        internal static string ErrorCreatingIdentifier {
            get {
                return ResourceManager.GetString("ErrorCreatingIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiba történt az új hivatkozás létrehozásakor..
        /// </summary>
        internal static string ErrorCreatingLink {
            get {
                return ResourceManager.GetString("ErrorCreatingLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiba történt a névjegy létrehozása közben..
        /// </summary>
        internal static string ErrorCreatingPerson {
            get {
                return ResourceManager.GetString("ErrorCreatingPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiba történt a cím vagy azonosító törlésekor..
        /// </summary>
        internal static string ErrorDeletingAttribute {
            get {
                return ResourceManager.GetString("ErrorDeletingAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiba történt a fájl törlésekor..
        /// </summary>
        internal static string ErrorDeletingBlob {
            get {
                return ResourceManager.GetString("ErrorDeletingBlob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiba történt a kategória törlésekor..
        /// </summary>
        internal static string ErrorDeletingCategory {
            get {
                return ResourceManager.GetString("ErrorDeletingCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiba történt a dátum törlésekor..
        /// </summary>
        internal static string ErrorDeletingDate {
            get {
                return ResourceManager.GetString("ErrorDeletingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiba történt az elem törlésekor..
        /// </summary>
        internal static string ErrorDeletingEntity {
            get {
                return ResourceManager.GetString("ErrorDeletingEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiba történt a hivatkozás törlésekor..
        /// </summary>
        internal static string ErrorDeletingLink {
            get {
                return ResourceManager.GetString("ErrorDeletingLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiba történt a cégek keresése közben..
        /// </summary>
        internal static string ErrorFindingCompanies {
            get {
                return ResourceManager.GetString("ErrorFindingCompanies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiba történt a dokumentumok keresése közben..
        /// </summary>
        internal static string ErrorFindingDocuments {
            get {
                return ResourceManager.GetString("ErrorFindingDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiba történt a mappák keresése közben..
        /// </summary>
        internal static string ErrorFindingFolders {
            get {
                return ResourceManager.GetString("ErrorFindingFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiba történt a címek és azonosítók betöltése közben..
        /// </summary>
        internal static string ErrorLoadingAttributes {
            get {
                return ResourceManager.GetString("ErrorLoadingAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiba történt az adatfájlok betöltése közben..
        /// </summary>
        internal static string ErrorLoadingBlobs {
            get {
                return ResourceManager.GetString("ErrorLoadingBlobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiba történt a kategóriák betöltése közben..
        /// </summary>
        internal static string ErrorLoadingCategories {
            get {
                return ResourceManager.GetString("ErrorLoadingCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiba történt a cég betöltése közben..
        /// </summary>
        internal static string ErrorLoadingCompany {
            get {
                return ResourceManager.GetString("ErrorLoadingCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiba történt a dátumok betöltése közben..
        /// </summary>
        internal static string ErrorLoadingDates {
            get {
                return ResourceManager.GetString("ErrorLoadingDates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiba történt a dokumentum betöltése közben..
        /// </summary>
        internal static string ErrorLoadingDocument {
            get {
                return ResourceManager.GetString("ErrorLoadingDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiba történt a mappa betöltése közben..
        /// </summary>
        internal static string ErrorLoadingFolder {
            get {
                return ResourceManager.GetString("ErrorLoadingFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiba történt a hivatkozások betöltése közben..
        /// </summary>
        internal static string ErrorLoadingLinks {
            get {
                return ResourceManager.GetString("ErrorLoadingLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiba történt a névjegy betöltése közben..
        /// </summary>
        internal static string ErrorLoadingPerson {
            get {
                return ResourceManager.GetString("ErrorLoadingPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiba történt a névjegyek betöltése közben..
        /// </summary>
        internal static string ErrorLoadingPersons {
            get {
                return ResourceManager.GetString("ErrorLoadingPersons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Az adatséma betöltése nem sikerült. A program leáll..
        /// </summary>
        internal static string ErrorLoadingSchema {
            get {
                return ResourceManager.GetString("ErrorLoadingSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiba történt a cím módosítása közben..
        /// </summary>
        internal static string ErrorModifyingAddress {
            get {
                return ResourceManager.GetString("ErrorModifyingAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiba történt a kategória módosításakor..
        /// </summary>
        internal static string ErrorModifyingCategory {
            get {
                return ResourceManager.GetString("ErrorModifyingCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiba történt a dátum módosításakor..
        /// </summary>
        internal static string ErrorModifyingDate {
            get {
                return ResourceManager.GetString("ErrorModifyingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiba történt az azonosító módosításakor..
        /// </summary>
        internal static string ErrorModifyingIdentifier {
            get {
                return ResourceManager.GetString("ErrorModifyingIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiba történt a hivatkozás módosításakor..
        /// </summary>
        internal static string ErrorModifyingLink {
            get {
                return ResourceManager.GetString("ErrorModifyingLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiba történt az elem feloldásakor..
        /// </summary>
        internal static string ErrorOpeningEntity {
            get {
                return ResourceManager.GetString("ErrorOpeningEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiba történt a fájl mentésekor..
        /// </summary>
        internal static string ErrorSavingBlob {
            get {
                return ResourceManager.GetString("ErrorSavingBlob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiba történt az elem mentésekor..
        /// </summary>
        internal static string ErrorSavingEntity {
            get {
                return ResourceManager.GetString("ErrorSavingEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiba történt a művelet végrehajtása közben. A hiba leírása: {0} A hiba bekerült a hibanaplóba..
        /// </summary>
        internal static string ErrorTemplate {
            get {
                return ResourceManager.GetString("ErrorTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiba történt a bejelentkezésnél. A program leáll..
        /// </summary>
        internal static string ErrorUserLogin {
            get {
                return ResourceManager.GetString("ErrorUserLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiba történt a kijelentkezésnél..
        /// </summary>
        internal static string ErrorUserLogoff {
            get {
                return ResourceManager.GetString("ErrorUserLogoff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Érvénytelen érték, vagy nem megfelelő formátum..
        /// </summary>
        internal static string InvalidValue {
            get {
                return ResourceManager.GetString("InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verzió eltérés! A törlendő elemet valószínűleg egy másik felhasználó (vagy Ön egy másik ablakban) módosította vagy törölte, amióta Ön megnyitotta. Az adatok felülírása a más által elvégzett módosítások elvesztését okozhatja..
        /// </summary>
        internal static string InvalidVersionDelete {
            get {
                return ResourceManager.GetString("InvalidVersionDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verzió eltérés! A módosítandó elemet valószínűleg egy másik felhasználó (vagy Ön egy másik ablakban) módosította, amióta Ön megnyitotta. Az adatok felülírása a más által elvégzett módosítások elvesztését okozhatja..
        /// </summary>
        internal static string InvalidVersionModify {
            get {
                return ResourceManager.GetString("InvalidVersionModify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Séma betöltése....
        /// </summary>
        internal static string LoadingSchema {
            get {
                return ResourceManager.GetString("LoadingSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Módosítva.
        /// </summary>
        internal static string Modified {
            get {
                return ResourceManager.GetString("Modified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Csak olvasható.
        /// </summary>
        internal static string ReadOnly {
            get {
                return ResourceManager.GetString("ReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menti a változtatásokat?.
        /// </summary>
        internal static string SaveChanges {
            get {
                return ResourceManager.GetString("SaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Találatok száma: {0}.
        /// </summary>
        internal static string SearchResultCount {
            get {
                return ResourceManager.GetString("SearchResultCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Egyszerre csak egy elem módosítható..
        /// </summary>
        internal static string SingleModify {
            get {
                return ResourceManager.GetString("SingleModify", resourceCulture);
            }
        }
    }
}
